### ISSUE TITLE
Error on updating student response - PUT /api/assignment/<assignment_id>/response/<assignment_response_id>/student/<student_id>

### ISSUE THREAD

**Issue by EricHusa** [sarpongdk/fopd-flask-api#12]
"PUT /api/assignment/3e0ab69d-c551-483b-8fa9-5f6b4baa668f/response/5e8496ac-934a-4c4e-a91c-7c7f03aad928/student/225cab37-0d79-483f-b084-ad553fa4f02f HTTP/1.1" 500 -

  
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type integer: "3e0ab69d-c551-483b-8fa9-5f6b4baa668f"
LINE 3: WHERE assignment_responses.assignment_id = '3e0ab69d-c551-48...
                                                   ^

The above exception was the direct cause of the following exception:

  File "/Users/eric/PycharmProjects/testback/fopd-flask-api/fopd/assignment_responses/routes.py", line 174, in update_student_response
    assignment_response = AssignmentResponse.query.filter_by(assignment_id = assignment_id, public_id = assignment_response_id, student_id = student_id).first()

sqlalchemy.exc.DataError: (psycopg2.errors.InvalidTextRepresentation) invalid input syntax for type integer: "3e0ab69d-c551-483b-8fa9-5f6b4baa668f"
LINE 3: WHERE assignment_responses.assignment_id = '3e0ab69d-c551-48...
                                                   ^

[SQL: SELECT assignment_responses.id AS assignment_responses_id, assignment_responses.response AS assignment_responses_response, assignment_responses.submitted AS assignment_responses_submitted, assignment_responses.comments AS assignment_responses_comments, assignment_responses.public_id AS assignment_responses_public_id, assignment_responses.student_id AS assignment_responses_student_id, assignment_responses.assignment_id AS assignment_responses_assignment_id 
FROM assignment_responses 
WHERE assignment_responses.assignment_id = %(assignment_id_1)s AND assignment_responses.public_id = %(public_id_1)s AND assignment_responses.student_id = %(student_id_1)s 
 LIMIT %(param_1)s]
[parameters: {'assignment_id_1': '3e0ab69d-c551-483b-8fa9-5f6b4baa668f', 'public_id_1': '5e8496ac-934a-4c4e-a91c-7c7f03aad928', 'student_id_1': '225cab37-0d79-483f-b084-ad553fa4f02f', 'param_1': 1}]
(Background on this error at: http://sqlalche.me/e/9h9h)

**Comment by sarpongdk** [comment]
Fixed, lemme know and close
