### ISSUE TITLE
FOP API

### ISSUE THREAD

**Issue by EricHusa** [sarpongdk/fopd-flask-api#7]
For the external FOP api, I see that you have things set up, but I don't know how to access them. Here is what I propose:

Login
Store the login credentials locally on your side. Make a public log in function that I can call that will just return the auth cookie

Images:
Don't mess with storing and retrieving images.  I will simply call the Login function to get the auth and will call for the image directly on the page (very simple on my side)

Environment data:
There a are attributes in the data from the endpoint, "temperature" and "humidity". For each attribute, I need an array of points { x:ts, y:value }.I can generate the timestamps for the URL. So from your side I either need:

1. An endpoint that takes a URL and directly returns the data array(s)
2. An endpoint that takes a URL and returns the raw JSON
3. Just the login endpoint and I handle it on my side like the images.

Let me know what you will be doing for the Environment data. 

For this issue, Login endpoint is higher priority. The Environment data endpoint is lower priority that everything else.

**Comment by sarpongdk** [comment]
You can test it out and close it when its ok with you. Both login and environment

**Comment by EricHusa** [comment]
This is what I'm seeing from the endpoint

<img width="965" alt="Screen Shot 2020-05-03 at 12 21 59 PM" src="https://user-images.githubusercontent.com/45300328/80920988-f8cb9d00-8d38-11ea-980b-b2dc87c09cf2.png">

**Comment by sarpongdk** [comment]
fixed
