### ISSUE TITLE
Error on deleting experiments

### ISSUE THREAD

**Issue by EricHusa** [sarpongdk/fopd-flask-api#8]
Error message:

"DELETE /api/experiment/32fa6945-6136-4a40-b386-26e3b756d92e/teacher/03dc863d-7811-411f-b70b-4a0837ab5c0f HTTP/1.1" 500 -

  **File "/Users/eric/PycharmProjects/testback/fopd-flask-api/fopd/experiments/routes.py", line 140, in delete_experiment
    if experiment.teacher != teacher:
AttributeError: 'BaseQuery' object has no attribute 'teacher'**

**Comment by sarpongdk** [comment]
fixed
